services:
  backend:
    build:
      context: ./taskly-backend
    ports:
      - '5001:5000'
    environment:
      - FLASK_APP=app # Change 'myapp' to your actual Flask package name
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=True
    volumes:
      - ./taskly-backend:/app # Sync local changes
      - sqlite_data:/app/instance # Persist SQLite database

  frontend:
    build:
      context: ./taskly-frontend #
      args:
        VITE_API_BASE_URL: 'http://localhost:5001/'
    ports:
      - '3000:80' # Map React frontend to port 3000
    environment:
      - VITE_API_BASE_URL=http://localhost:5001/ # Set API URL inside Docker
    depends_on:
      - backend
    volumes:
      - ./taskly-frontend:/app # Ensure .env is written inside the container

volumes:
  sqlite_data:
